# Site settings
title: Using MathJax
baseurl: "/using-mathjax-in-markdown" # The subpath of your site.
url: "https://george-hawkins.github.io" # The base hostname and protocol for your site.

# Build settings
markdown: kramdown
